### ISSUE TITLE
Empty connections when Host after Client

### ISSUE THREAD

**Issue by piotr-shishkov** [Chykary/FizzyFacepunch#13] opened 2021-05-01 15:00 UTC
I noticed strange bug. If you join friend server, then leave and create new server as host and same friend enter your server, it's cause strange things like: 

- Server spawn client player prefab twice 
- Serves tries to remove/unspawn client prefab twice

Also, count of empty (ghost) connection depends on how much you joined your friend when he was host. So if you joined his server 4 times and after it you start as host and fried joins your server, you will got 4 empty connections. 

I noticed this bug in my project, then I created a new one simple project and this bug happened too. 

Also I think that this bug somehow connected with another one, I opened issue for it recently: [Issue Link](https://github.com/Chykary/FizzyFacepunch/issues/12)

**Comment by DarklightStudios** [comment] 2021-05-12 12:46
Having the same problem here

**Comment by Chykary** [comment] 2021-05-12 21:25
Can you check if this is fixed with the latest release?

**Comment by DarklightStudios** [comment] 2021-05-12 22:42
> Can you check if this is fixed with the latest release?

I'll test it a bit later, for now I managed to solve the issue by adding:

`SteamNetworkingSockets.OnConnectionStatusChanged -= OnConnectionStatusChanged;`

and 

`connToMirrorID = new BidirectionalDictionary<Connection, int>();
 steamIDToMirrorID = new BidirectionalDictionary<SteamId, int>();`

into Disconnect() in NextServer.cs

I think I also added a similar line to unsubscribe from the event in NextClient, but both the unsubscribe lines still resulted in the issue. Resetting the two above BidirectionalDictionary variables is what I believe fixed the issue. Left the unsubscribe there just incase.

I'll give the latest version a test sometime tomorrow and post feedback.

**Comment by DarklightStudios** [comment] 2021-05-13 10:28
Okay, I've tested the latest release with the latest version of Mirror. It now works as it should. I did notice that I still get NextServer.cs is still sending `OnReceivedError.Invoke(connectionId, new Exception("ERROR Unknown Connection"));` (from `Send()`) on the Host if they disconnect.

Currently that's not an issue as the main problem is now sorted. Out of curiosity though, if I instead reset the variables in Disconnect as per my previous post, what problems could that cause? It did solve both issues before the update and worked fine with 2 players. I'm not sure if it would be a problem with more than 2 though.

But other than all that, I guess you could say it's solved. Not sure if it solves all of OP's problems though.

**Comment by piotr-shishkov** [comment] 2021-05-13 15:54
Okay, i tested it, now where is no bug with  empty connections, but if client disconnects appears an errors that **trying to send on unknown connection**

Screen:
![image](https://user-images.githubusercontent.com/70975176/118151738-9bbef880-b41c-11eb-9234-5bf51961f29b.png)

**Comment by DarklightStudios** [comment] 2021-05-13 18:26
Yeah that's the same error I mentioned in my last post. Should all still work regardless but just waiting for @Chykary to know if what I did to fix those errors by resetting the connToMirrorID and steamIDToMirrorID variables on Disconnect is good or bad, as that did solve those errors before.

**Comment by LukeSeers** [comment] 2022-02-03 09:09
> I noticed strange bug. If you join friend server, then leave and create new server as host and same friend enter your server, it's cause strange things like:
> 
> * Server spawn client player prefab twice
> * Serves tries to remove/unspawn client prefab twice
> 
> Also, count of empty (ghost) connection depends on how much you joined your friend when he was host. So if you joined his server 4 times and after it you start as host and fried joins your server, you will got 4 empty connections.
> 
> I noticed this bug in my project, then I created a new one simple project and this bug happened too.
> 
> Also I think that this bug somehow connected with another one, I opened issue for it recently: [Issue Link](https://github.com/Chykary/FizzyFacepunch/issues/12)

I couldn't reproduce the problem you was describing in the latest master branch. So, I will close this ticket. 
For the meantime since their hasn't been a newer release yet, please download from the master branch: https://github.com/Chykary/FizzyFacepunch/tree/master


If this problem happens again please reopen this ticket by replying thanks.

**Closed as completed by LukeSeers** 2022-02-03 09:09 UTC
