### ISSUE TITLE
Every new connection as client adds additional LoadScene

### ISSUE THREAD

**Issue by piotr-shishkov** [Chykary/FizzyFacepunch#12] opened 2021-05-01 11:35 UTC
I have a problem with FizzyFacepunch (with KcpTransport all works fine). When I connect to my friend's server for the first time all ok, but every next time I connect it's loading one more map. For example on third connection: 
![image](https://user-images.githubusercontent.com/70975176/116781225-4c76e080-aa8a-11eb-8684-3e7368b64414.png)
I think that problem with FizzyFacepunch library, because with any other transports all works fine.

**Comment by Chykary** [comment] 2021-05-12 21:25
Can you check if this is fixed with the latest release?

**Comment by LukeSeers** [comment] 2022-02-03 09:13
> I have a problem with FizzyFacepunch (with KcpTransport all works fine). When I connect to my friend's server for the first time all ok, but every next time I connect it's loading one more map. For example on third connection: ![image](https://user-images.githubusercontent.com/70975176/116781225-4c76e080-aa8a-11eb-8684-3e7368b64414.png) I think that problem with FizzyFacepunch library, because with any other transports all works fine.

I couldn't reproduce the problem you was describing in the latest master branch. So, I will close this ticket. 
For the meantime since their hasn't been a newer release yet, please download from the master branch: https://github.com/Chykary/FizzyFacepunch/tree/master


If this problem happens again please reopen this ticket by replying thanks.

**Closed as completed by LukeSeers** 2022-02-03 09:13 UTC
